### ISSUE TITLE
Atom not maximized on start

### ISSUE THREAD

**Issue by binaryfunt** [cakecatz/flex-toolbar#156]
### Version info

Windows 10 v1803
Atom 1.34.0
flex-toolbar 2.1.2

### Steps to reproduce

1. Maximise the Atom window 
1. Close Atom
1. Open Atom - the window will open in a non-maximised state (i.e. restored window state)

I have narrowed this down to the flex-toolbar package. When it's disabled, Atom opens maximised as expected.

N.B. when the window opens in a non-maximised state, it's the same size as a maximised window due to [this issue with Atom](https://github.com/atom/atom/issues/10720)

**Comment by UziTech** [comment]
I can't seem to reproduce this. The window opens maximized for me. I can't find any reason flex-toolbar should affect the size of the window.

It could be something that is fixed in beta versions of Windows or Atom.

### Version info
Windows 10 Pro v1903 Insider Build 18346.1
Atom v1.35.0-beta0
flex-toolbar 2.1.2

**Comment by binaryfunt** [comment]
On further investigation, it seems to happen at random? Today Atom opened maximised as expected for 4 out of the 5 times I've opened it (with all packages enabled). Maybe the problem isn't related to flex-toolbar and it was just a fluke the last time?

**Comment by UziTech** [comment]
thanks for the update

**Comment by binaryfunt** [comment]
Just a bit of further info on this from further testing: it happens sporadically/unpredictably when opening or reloading Atom. I notice that every single time Atom is reloaded (even in safe mode), the window is temporarily unmaximized/restored before being maximised again, so the cause of the problem is probably somewhere in there and not flex-toolbar's fault.

**Comment by raphtlw** [comment]
This issue still occurs in Windows 10, atom 1.41.0. Can be replicated in Safe Mode.

**Comment by UziTech** [comment]
Safe Mode disables extensions by default, so if it happens in safe mode then it is most likely not a problem with any extension and should be reported to [Atom](https://github.com/atom/atom/issues)
